-- THESE TWO QUERIES ARE ALTERNATIVE TO THE CURSOR
-- ROW SET OPERATIONS (CURSOR) VS SET BASED OPERATIONS
-- SET BASES ARE WAY FASTER (150 TIMES AT LEAST) AND SHOULD BE USED AWALYS

-- #EXAMPLE 1
SELECT * FROM 
tblTransaction
WHERE EmployeeNumber IN (
SELECT EmployeeNumber FROM tblEmployee
WHERE EmployeeNumber BETWEEN 120 AND 299)

-- #EXAMPLE 2
SELECT T.* FROM 
tblTransaction AS T
RIGHT JOIN tblEmployee AS E
ON T.EmployeeNumber = E.EmployeeNumber
WHERE E.EmployeeNumber BETWEEN 120 AND 299 AND T.EmployeeNumber IS NOT NULL