BEGIN TRAN
UPDATE tblEmployee SET EmployeeNumber = 122 WHERE EmployeeNumber = 123 -- SHARED LOCK -> UPDATE LOCK -> EXCLUSIVE LOCK
WAITFOR DELAY '00:00:10'
ROLLBACK TRAN -- RELEASES THE LOCK

GO
SELECT * FROM tblEmployee