--FOREIGN KEY  -> SEEK
--REGULAR COLUMNS -> SCAN

/* FOREIGN KEY 
			 NO ACTION -> RAISES AN ERROR IF YOU CHANGE IT AND IF THERE IS SOMETHING RELYING ON IT
			 CASCADE
			 SET NULL
			 SET DEFAULT
*/
BEGIN TRAN
ALTER TABLE EmployeeTransaction ALTER COLUMN EmployeeNumber INT NULL
ALTER TABLE EmployeeTransaction ADD CONSTRAINT DF_EmployeeTransaction DEFAULT 124 FOR EmployeeNumber
-- ADD FOREGIN KEY
ALTER TABLE EmployeeTransaction WITH NOCHECK
ADD CONSTRAINT FK_Transaction_EmployeeNumber FOREIGN KEY (EmployeeNumber)
REFERENCES Employee(EmployeeNumber)
ON UPDATE CASCADE -- UPDATES ALL REFERENCE - WITHOUT IT IT THROWS AN ERROR
ON DELETE SET DEFAULT -- SETS ALL OF THE DELETED TRANSACTIONS TO A DEFAULT EMPLOYEE NUMBER => 124
-- ON DELETE NO ACTION  -- THROWS AN ERROR DUE TO REFERENCED KEYS
-- ON UPDATE SET NULL -- BOTH VALUES REFERENCE AND ORIGINAL IS SET TO NULL
-- ON UPDATE SET DEFAULT -- SETS BOTH OF THE BOTH VALUES REFERENCE AND ORIGINAL TO DEFAULT => 124

--UPDATE Employee
--SET EmployeeNumber = 9123
--OUTPUT inserted.*, deleted.*
--WHERE EmployeeNumber = 123
DELETE Employee
OUTPUT deleted.*
WHERE EmployeeNumber = 123


-- SHOW ALL EmployeeTransactions
SELECT E.EmployeeNumber, T.*
FROM Employee AS E
RIGHT JOIN EmployeeTransaction AS T
ON E.EmployeeNumber = T.EmployeeNumber
WHERE T.Amount IN (-179.47,957.03,-967.36,786.22)
SELECT * FROM Employee WHERE Employee.EmployeeNumber = 124

ROLLBACK TRAN
