-- DIFFERENT RESULTS FOR THESE TWO VERY SIMILLAR QUERIES

-- MUST BE IN EMPLOYEE AND EMPLOYEETRANSACTION AND NOT 126-129
-- THIS QUERY IS EQUIVALENT TO INNER JOIN
SELECT * FROM EmployeeTransaction AS T
WHERE EmployeeNumber IN 
	(SELECT EmployeeNumber FROM Employee WHERE EmployeeLastName NOT LIKE 'y%') 
ORDER BY EmployeeNumber  

-- MUST BE IN EMPLOYEETRANSACTION AND NOT 126-129
-- THIS QUERY IS EQUIVALENT TO LEFT JOIN
SELECT * FROM EmployeeTransaction AS T
WHERE EmployeeNumber NOT IN 
	(SELECT EmployeeNumber FROM Employee WHERE EmployeeLastName LIKE 'y%') 
ORDER BY EmployeeNumber  