/*
PERCENTAGE OF NUMBERS
	1
	3
	6
	7
	7
MEAN: SUM(1,3,6,7,7) / COUNT = 4.8  -- AVG()
MODE: 7 -- TAKES THE ONE THAT IS MOST FREQUENTLY USED
MEDIAN: 6 --  SORT THEM BY ASC/DESC ORDER AND TAKES THE ONE IN THE MIDDLE // IF THERE IS UNEVEN NUMBER OF ROWS IT TAKES THOSE TWO VALUES IN THE MIDDLE AND GETS MEDIUM OF THAT 
PERCENTILE 50% IS ANOTHER WAY TO EXPRESS MEDIAN
*/

-- MULTIPLYING PERCENT_RANK to 100 to get the PERCENTILE

--SELECT A.EmployeeNumber, A.AttendanceMonth, A.NumberAttendance,
--CUME_DIST() OVER (PARTITION BY E.EmployeeNumber ORDER BY A.NumberAttendance) AS CUMEDIST, 
--PERCENT_RANK () OVER (PARTITION BY E.EmployeeNumber ORDER BY A.NumberAttendance ) *100 AS PERCENTRANK 
--FROM Employee AS E INNER JOIN Attendance AS A  
--ON E.EmployeeNumber = A.EmployeeNumber

SELECT DISTINCT EmployeeNumber,
PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY NumberAttendance) OVER (PARTITION BY EmployeeNumber) as AverageCont, --CONTINUES RANGE -> LOOKS AT 50%(OR WHATEVER PERCENTAGE NUMBER YOU SPECIFY) AND GETS THE VALUE WHICH IS IN THIS CASE FOR 123 EMPLOYEE 16.5
PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY NumberAttendance) OVER (PARTITION BY EmployeeNumber) as AverageDisc -- DESCRETE NUMBER -> TAKES THE POINT/NUMBER CLOSES TO THE 50% (OR WHATEVER PERCENTAGE NUMBER YOU SPECIFY), BASICALLY ROUNDING IT
FROM Attendance