ALTER TABLE Employee
ADD
	ValidFrom DateTime2(2) GENERATED ALWAYS AS ROW START CONSTRAINT def_ValidFrom DEFAULT  SYSUTCDATETIME(),
	ValidTo Datetime2(2) GENERATED ALWAYS AS ROW END CONSTRAINT def_ValidTo DEFAULT CONVERT(DATETIME2(2),'9999-12-31 23:59:59'),
	PERIOD FOR SYSTEM_TIME (ValidFrom,ValidTo)

SELECT * FROM Employee

ALTER TABLE Employee
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.EmployeeHistory2))