BEGIN TRANSACTION
CREATE SEQUENCE newSeq AS INT
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999
CYCLE
SELECT NEXT VALUE FOR newSeq as NextValue
ROLLBACK TRANSACTION

GO

-- CREATE SEQUANCE OUTSIDE TRANSACTION
CREATE SEQUENCE newSeqeunce AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1
CACHE 50

-- ADD SEQUANCE TO EMPLOYEETRANSACTION
ALTER TABLE EmployeeTransaction
ADD NextNumber INT CONSTRAINT DF_Transaction DEFAULT NEXT VALUE FOR newSeqeunce


BEGIN TRANSACTION
SELECT * FROM EmployeeTransaction
INSERT INTO EmployeeTransaction(Amount, DateOfTransaction, EmployeeNumber)
VALUES (1,'2017-01-01',123)
SELECT * FROM EmployeeTransaction WHERE EmployeeNumber = 123

UPDATE EmployeeTransaction
SET NextNumber = NEXT VALUE FOR newSeqeunce
WHERE NextNumber IS NULL
SELECT * FROM EmployeeTransaction

ROLLBACK TRANSACTION
-- SEQUNACE DOESNT GET UNDONE IN THE TRANSACTION
SELECT * FROM sys.sequences


-- RESTART SEQUANCE
ALTER SEQUENCE newSeqeunce
RESTART -- OR RESTART WITH ANOTHER NUMBER -> RESTART WITH 5555


-- DROP ORDER TO DROP COLUMN, YOU NEED TO DROP EVERYTHING RELATED TO THAT SEQUANCE
-- BECOUSE IT'S BEING REFERENCED
ALTER TABLE EmployeeTransaction
DROP DF_Transaction
ALTER TABLE EmployeeTransaction
DROP COLUMN NextNumber
DROP SEQUENCE newSeqeunce