DROP TABLE #tblXML
GO
CREATE TABLE #tblXML(XmlCol XML)
GO
-- ONE WAY OF INSERING DATA
BULK INSERT #tblXML FROM '[ INSERT IN HERE YOUR PATH ON THE DISK (e.g C:\USERS\USER\)]\SQL-70-461-and-70-761\Section 41 - Other XML considerations\XML\SampleDataBulkInsert.txt'

SELECT * FROM #tblXML


-- ANOTHER WAY IS USING OPENROWSET
DROP TABLE #tblXML
GO
CREATE TABLE #tblXML(IntCol INT,XmlCol XML)
GO

INSERT INTO #tblXML(XmlCol)
SELECT * FROM 
OPENROWSET(BULK '[ INSERT IN HERE YOUR PATH ON THE DISK (e.g C:\USERS\USER\)]\SQL-70-461-and-70-761\Section 41 - Other XML considerations\XML\SampleDataOpenRowset.txt', SINGLE_BLOB) AS X

SELECT * FROM #tblXML
